### ISSUE TITLE
extract tar command issue

### ISSUE THREAD

**Issue by rahulroy0611** [Micro0x00/Arsenal#5]
Go-lang installation (Manual)
 sudo apt-get remove -y golang-go
 sudo rm -rf /usr/local/go
 wget https://go.dev/dl/go1.20.4.linux-amd64.tar.gz
 sudo tar -xvf go1.19.1.linux-amd64.tar.gz    ===============> **should replace with sudo tar -xvf go1.20.4.linux-amd64.tar.gz [replace 1.19.1 with 1.20.4]**
 sudo mv go /usr/local
 nano /etc/profile or .profile
 export GOPATH=$HOME/go
 export PATH=$PATH:/usr/local/go/bin
 export PATH=$PATH:$GOPATH/bin 
 source /etc/profile #to update you shell dont worry

**Comment by Micro0x00** [comment]
thanks for help
